Accept SSL certificates by providing a URL to use cert from within a jar
pgjdbc/r2dbc-postgresql pull request #318
Opened 2020-08-17 20:38 UTC by Isabek

[resolves #313]

Make sure that:

- [*] You have read the [contribution guidelines](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/.github/CONTRIBUTING.adoc).
- [*] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [*] You use the code formatters provided [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/master/intellij-style.xml) and have them applied to your changes. Don't submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

 

#### Issue description

 
#### New Public APIs

#### Additional context

2020-08-18 15:12 UTC, Squiry commented
@Isabek your changes need to be covered by tests
1. Integration test with classpath url [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/test/java/io/r2dbc/postgresql/client/ReactorNettyClientIntegrationTests.java#L674).
2. Test cases for configuration parsing and mapping string values to URLs [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/test/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProviderUnitTests.java).
3. Test cases for possible mistakes in configuration (like file/resource doesn't exist) [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/test/java/io/r2dbc/postgresql/PostgresqlConnectionConfigurationUnitTests.java).

2020-09-07 09:04 UTC, mp911de commented
`classpath:` is a Spring-specific feature hence it's not applicable in our context. Please use `ClassLoader.getResource(…)` to construct an URL pointing to class-path resources.

2020-10-15 08:43 UTC, mp911de commented
Any update on this pull request? If not, we will close this one in a few days.

2020-10-30 08:54 UTC, Isabek commented
@mp911de sorry. I will update it on weekends.

2020-11-07 11:49 UTC, Isabek commented
@mp911de I have pushed my last changes. Could you review it, please?

2020-12-10 13:33 UTC, davecramer commented
@Isabek can we also update the README to reflect this option ?

2020-12-10 13:57 UTC, mp911de requested changes

2020-12-10 13:57 UTC, mp911de commented on src/main/java/io/r2dbc/postgresql/util/Assert.java
> +        URL url = classLoader != null ? classLoader.getResource(path) : ClassLoader.getSystemResource(path);
How is the classloader supposed to be null?

2020-12-10 13:57 UTC, mp911de commented on src/main/java/io/r2dbc/postgresql/util/Assert.java
> +    private static final String CLASSPATH_PREFIX = "classpath:";
That isn't a generally supported URL scheme. It only works because Spring is on the class path.

2020-12-10 13:57 UTC, mp911de commented on src/main/java/io/r2dbc/postgresql/util/Assert.java
> +    public static URL requireUrlExistsOrNull(@Nullable String path, String message) {
We should revert changes to the `Assert` class and instead, introduce rather an utility method to figure out, whether the given `ConnectionFactoryOption` tries to point to a real file or to a URL. Checking for a scheme would be a good approach if the configured string doesn't point to a file.

We might still run into an ambiguity on windows (`c:\foo\bar.crt` vs. `classpath:foo.crt` or `classpath:/foo`). Not sure how to resolve that.

2020-12-14 09:59 UTC, mp911de commented
@Isabek I'm happy to take this PR from here as it requires a bit of experimentation. WDYT?

2020-12-14 10:04 UTC, Isabek commented
> @Isabek I'm happy to take this PR from here as it requires a bit of experimentation. WDYT?

Sure.

2021-02-18 10:31 UTC, closed without merging

2021-02-18 10:31 UTC, mp911de commented
Thank you for your contribution. That's merged, polished, and backported now.