Add IntervalCodec and Interval class
pgjdbc/r2dbc-postgresql pull request #353
Opened 2020-11-13 21:21 UTC by frankgh

Support the Postgres Interval type by adding the IntervalCodec.

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/.github/CONTRIBUTING.adoc).
- [ ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [ ] You use the code formatters provided [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/master/intellij-style.xml) and have them applied to your changes. Don't submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

#### Issue description

https://github.com/pgjdbc/r2dbc-postgresql/issues/345
 
#### New Public APIs

Interval and IntevalCodec classes

2020-12-11 10:55 UTC, mp911de commented
Wow, this is a pretty decent PR. I'm going to take it from here.

2020-12-11 11:32 UTC, mp911de requested changes

2020-12-11 11:32 UTC, mp911de commented on src/test/java/io/r2dbc/postgresql/codec/IntervalUnitTests.java
> +                new Object[]{Interval.of(Period.of(45, 6, 9), Duration.ofSeconds(443121)), "45 yr 6 mon 14 day 3 hr 5 min 21.0 sec"},
There seems something to be off in the parser. The resulting `Interval` reports 45 hours.

2020-12-13 21:27 UTC, closed without merging

2020-12-13 21:27 UTC, mp911de commented
Thank you for your contribution. That's merged, polished, and backported now.

2020-12-13 22:53 UTC, frankgh commented
thanks @mp911de , I'm eager for more contributions. I noticed that you already addressed a few things on this PR.